/*
* generated by Xtext
*/
package org.provus.atm.command.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.provus.atm.command.services.CommandGrammarAccess;

public class CommandParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CommandGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.provus.atm.command.parser.antlr.internal.InternalCommandParser createParser(XtextTokenStream stream) {
		return new org.provus.atm.command.parser.antlr.internal.InternalCommandParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CommandGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CommandGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
