/*
 * generated by Xtext
 */
package org.provus.atm.command;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CommandRuntimeModule extends org.provus.atm.command.AbstractCommandRuntimeModule {

}
