/*
* generated by Xtext
*/
package org.provus.atm.command;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CommandStandaloneSetup extends CommandStandaloneSetupGenerated{

	public static void doSetup() {
		new CommandStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

