/*
 * generated by Xtext
 */
package org.provus.atm.command.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CommandUiModule extends org.provus.atm.command.ui.AbstractCommandUiModule {
	public CommandUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
