/*
 * generated by Xtext
 */
package org.provus.atm.command.ui.contentassist

import org.provus.atm.command.ui.contentassist.AbstractCommandProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CommandProposalProvider extends AbstractCommandProposalProvider {
}
