/*
* generated by Xtext
*/
package org.provus.atm.command;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CommandUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.provus.atm.command.ui.internal.CommandActivator.getInstance().getInjector("org.provus.atm.command.Command");
	}
	
}
