/*
 * generated by Xtext
 */
package org.provus.atm.command.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCommandValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.provus.atm.command.command.CommandPackage.eINSTANCE);
		return result;
	}
}
